#' Example HisD DNA Sequences
#'
#' A dataset containing the HisD TA1538 mutant and LT2 wild-type DNA sequences
#' For use as an example in the DNA translate.
#'
#' Data was generated by sanger sequencing the PCR fragments produced from the DNA of salmonella cerevisiae
#' Strains were grown, harvested, and PCR was conducted by Aiden Hewitt.
#'
#' @format A data frame with 2 columns:
#' \describe{
#'   \item{name}{the name of the sequence}
#'   \item{sequence}{the DNA sequence string}
#' }
"exampleSequences"
