#' Reverses a specified sequence
#'
#' @param df a dataframe with exactly 2 columns, typically generated by the readSequence function in this package
#' @param name the name of the sequence that needs to be reversed
#'
#' @return the "same" dataframe but with the specified dataframe reversed
#' @export
#'
#' @examples
#' sequences <- reverseSequence(df, "HisD TA1538 Mutant Genotype")
#'
reverseSequence <- function(df, name) {
  row_index <- which(df$name == name) # find the row matching the name the user specified
  if (length(row_index) == 0) stop(paste("no sequence found with name:", name))  # stop if the name wasn't found that user messed up, write some kind of error for this
  df$sequence[row_index] <- paste(rev(strsplit(df$sequence[row_index], "")[[1]]), collapse = "")  # reverse the specified sequence and save back into df

  return(df)
}
