#' Reverses a specified sequence
#'
#' This function is useful if a sequence is transcribed by a ribosome in the opposite to the orientation as it was imported
#' This function is not intended to be used in isolation, but rather as a downstream process to the readSequences() function
#' The sequence name must match exactly with what is present, this will NOT reverse the protein sequence if it is already present, the user must re-run translateDNA to update the protein sequence
#' You as a user must know the "correct" orientation for your DNA sequence, there is no definitive "correct" direction
#'
#' @param df a dataframe with exactly 2 columns, typically generated by the readSequence function in this package
#' @param name a string containing the name of the sequence that needs to be reversed
#'
#' @return the "same" dataframe but with the specified sequence reversed
#' @export
#'
#' @examples
#' sequences <- reverseSequence(exampleSequences, "HisD TA1538 Mutant Genotype")
#'
reverseSequence <- function(df, name) {

  checkmate::assert_data_frame(df)
  checkmate::assert_string(name)
  checkmate::assert_true(name %in% df$name)

  row_index <- which(df$name == name) # find the row matching the name the user specified
  df$sequence[row_index] <- paste(rev(strsplit(df$sequence[row_index], "")[[1]]), collapse = "")  # reverse the specified sequence and save back into df by cutting it into list of characters and then pasting them in reverse order

  return(df)
}
