#' Translate a DNA sequence to a protein sequence
#'
#' @param df a dataframe with exactly 2 columns, typically generated by the readSequence function in this package
#' @param offset a number 0,1,2 that determines the reading frame offset from the start of the
#'
#'
#' @returns a dataframe with 3 columns, name, DNA sequence, protein sequence
#' @export
#'
#' @examples
#' protein_df <- translateDNA(DNA_df)
#'
translateDNA <- function(df, offset = 0) {
  codon_table <- c(
    TTT="F",
    TTC="F",
    TTA="L",
    TTG="L",
    CTT="L",
    CTC="L",
    CTA="L",
    CTG="L",
    ATT="I",
    ATC="I",
    ATA="I",
    ATG="M",
    GTT="V",
    GTC="V",
    GTA="V",
    GTG="V",
    TCT="S",
    TCC="S",
    TCA="S",
    TCG="S",
    CCT="P",
    CCC="P",
    CCA="P",
    CCG="P",
    ACT="T",
    ACC="T",
    ACA="T",
    ACG="T",
    GCT="A",
    GCC="A",
    GCA="A",
    GCG="A",
    TAT="Y",
    TAC="Y",
    TAA="*",
    TAG="*",
    CAT="H",
    CAC="H",
    CAA="Q",
    CAG="Q",
    AAT="N",
    AAC="N",
    AAA="K",
    AAG="K",
    GAT="D",
    GAC="D",
    GAA="E",
    GAG="E",
    TGT="C",
    TGC="C",
    TGA="*",
    TGG="W",
    CGT="R",
    CGC="R",
    CGA="R",
    CGG="R",
    AGT="S",
    AGC="S",
    AGA="R",
    AGG="R",
    GGT="G",
    GGC="G",
    GGA="G",
    GGG="G"
  )
  # Apply translation to each row's sequence
  df$protein <- sapply(df$sequence, function(seq) {
    seq <- substring(seq, offset + 1) # trim the start of the sequence by the offset, not every DNA sequence starts in frame
    codons <- strsplit(seq, "(?<=.{3})", perl = TRUE)[[1]] # split into 3-character codons, these depend on the offset the user just specified
    codons <- codons[nchar(codons) == 3] # drop incomplete codons at the end
    paste(codon_table[codons], collapse = "") # look up each codon and join into protein string
  })
  return(df)
}
